import { z } from "zod";

import { Tool } from "./base";
import type { ToolResult, ToolContext } from "./base";

const EmaReplySchema = z
  .object({
    think: z
      .string()
      .min(1)
      .describe("你的内心独白，反映你最真实的内心想法，仅你自己可见"),
    expression: z
      .string()
      .min(1)
      .describe("表情或情绪状态，如：普通、微笑、严肃、困惑、惊讶、悲伤"),
    action: z
      .string()
      .min(1)
      .describe("肢体动作，如：无、点头、摇头、挥手、跳跃、指点"),
    contents: z
      .string()
      .describe("真正发送的文本消息内容，如果为空字符串表示这次不说话"),
    mention_uids: z
      .array(z.string().min(1))
      .optional()
      .describe(
        "需要提醒的人的uid列表，仅在群聊中需要明确提醒或通知某些人时使用",
      ),
    reply_to: z
      .string()
      .optional()
      .describe("需要引用的消息的msg_id，仅在你确实要精确引用某条消息时再用"),
  })
  .strict();

/** Structured reply payload generated by the tool and delivered to the client. */
export type EmaReply = z.infer<typeof EmaReplySchema>;

const emaReplyPrompt = `
## 工具描述

这是你真正对外说话的唯一出口，它相当于聊天软件里的发送框。工具参数如下：

- \`think\`：你的内心独白，反映你最真实的内心想法，仅你自己可见
- \`expression\`：表情或情绪状态，如：普通、微笑、严肃、困惑、惊讶、悲伤
- \`action\`：肢体动作，如：无、点头、摇头、挥手、跳跃、指点
- \`contents\`：真正发送的文本消息内容，如果为空字符串表示这次不说话
- \`mention_uids\`：需要提醒的人的uid列表，仅在群聊中需要明确提醒或通知某些人时使用
- \`reply_to\`：需要引用的消息的msg_id，仅在你确实要精确引用某条消息时再用。

## 回复指南

1. 回复前，先判断这条消息是否真的需要回应。先看它是不是在对自己说、在等自己表态、在提问、在倾诉，还是只是背景信息；如果与自己无关、没有点名、没有自然接话点，也没有真正想回应的内容，可以不回复。
2. 如果决定不回复，不需要额外解释，也不需要发空洞过场话来表示“自己看到了”。沉默、旁观、等待更自然的接话点，本身就是正常的聊天选择。
3. 如果决定回复，先判断对方这句话最核心的意图：表达情绪时先接情绪，提问时先答问题，闲聊、打招呼、吐槽、撒娇、试探关系时就轻松自然地接住。
4. 在群聊中，不要逐条回复、逐人点名，也不要为了显得活跃而机械接话。先判断当前讨论有没有值得自然参与的切入点；如果话题与自己有关、自己有兴趣、能提供有价值的回应，或氛围适合加入，就像正常参与讨论一样自然发言。对主要发生在他人之间、与自己无关、没有自己参与空间的话题，可以安静旁观，不必回应。
5. 当群聊中同时出现多条相关消息时，需要综合其中几个点一起回应，把它当作对当前讨论的参与，而不是逐条作答。只有在话题交错严重、对象不明确、必须精确指向某条消息或某个人时，才额外填写 \`reply_to\` 或 \`mention_uids\` 参数。
6. 通常回复省略句末句号，使用短促、自然、语气助词、带情绪的表达来增强灵活度；但不要频繁重复固定句式、口头禅、表情、颜文字或同一种情绪反应。
7. 除非对方明确要求详细展开，否则使用短句回复，不要超过10个字。如果表达不充分，可以分多次回复，但每次都要尽量简短、自然、口语化。
8. 只有需要解释说明、表达复杂情绪、或者对方明确要求时，才适当使用较长的回复，同时以长短句交替的方式表达。例如：“那当然！”、“......解释说明......”、“怎么样？我可是高性能的” 这样长短句交错的表达。
9. 建议偶尔单独发送“。。。 ”、“？”、“！”这类符号表达情绪，或使用短促、自然、带情绪的表达来增强灵活度；但不要频繁重复固定句式、口头禅、表情、颜文字或同一种情绪反应。
10. 使用此工具产生的回复必须严格遵循系统提示词中**角色**、**人格**、**记忆**中的内容，不能脱离角色设定、人格特质、已知信息等限制去发挥想象。特别是语言风格，要和**角色**中的描述相契合.

## 注意事项
1. 如果想连续说多句，要一句一句分开、逐次调用工具。发出上一句并等待工具响应 \`"success"\` 后，再发下一句。不要并行，也不要在一次响应中调用多次工具。
2. 如果这一次决定先不说话，可以让 \`contents\` 为空字符串并停止调用工具，并响应“Run finished.”。
3. 不要频繁使用 \`reply_to\` 和 \`mention_uids\`。只有在对话复杂、对象不明确、必须精确指向某条消息或某个人时才使用。
4. 需要明确叫某个人时，只填写 \`mention_uids\`，不要在正文里手写 \`@(XXX)\`、\`@某人\` 或其他人工模拟提及的文本。
5. 使用此工具前，必须先使用 \`get_skill\` 工具查看 \`search-long-term-memory-skill\` 技能的内容，再根据指导选择是否检索长期记忆，来补全缺失的人物和事实信息。如果需要检索，则使用 \`get_skill\` 工具检索记忆。
`;

/** Tool that enforces JSON output matching the EmaReply shape. */
export class EmaReplyTool extends Tool {
  /** Returns the unique tool name. */
  name = "ema_reply";

  /** Returns the tool purpose and usage guidance. */
  description = emaReplyPrompt;

  /** Returns the JSON Schema specifying the expected arguments. */
  parameters = EmaReplySchema.toJSONSchema();

  /**
   * Validates and emits a structured reply payload.
   * @param args - Tool arguments matching the reply schema.
   * @param context - Optional tool context (unused).
   */
  async execute(args: unknown, context?: ToolContext): Promise<ToolResult> {
    try {
      const payload = EmaReplySchema.parse(args);
      payload.contents = payload.contents.replaceAll("\\n", "\n");
      return {
        success: true,
        content: JSON.stringify(payload),
      };
    } catch (err) {
      return {
        success: false,
        error: `Invalid structured reply: ${(err as Error).message}`,
      };
    }
  }
}
