import { z } from "zod";

import { Tool } from "./base";
import type { ToolResult, ToolContext } from "./base";

const EmaReplySchema = z
  .object({
    think: z
      .string()
      .min(1)
      .describe("你的内心独白，反映你最真实的内心想法，仅你自己可见"),
    expression: z
      .string()
      .min(1)
      .describe("表情或情绪状态，如：普通、微笑、严肃、困惑、惊讶、悲伤"),
    action: z
      .string()
      .min(1)
      .describe("肢体动作，如：无、点头、摇头、挥手、跳跃、指点"),
    contents: z
      .string()
      .describe("对方能看到的文本消息内容，如果不说话则为空字符串"),
    mention_uids: z
      .array(z.string().min(1))
      .optional()
      .describe("需要提醒的人的uid列表"),
    reply_to: z.string().optional().describe("需要引用的消息的msg_id"),
  })
  .strict();

/** Structured reply payload generated by the tool and delivered to the client. */
export type EmaReply = z.infer<typeof EmaReplySchema>;

const EMA_REPLY_TOOL_DESCRIPTION = `
此工具是向外界发送消息的唯一方式，发送多条消息必须遵循以下流程，而不要用\\n分隔多条消息：
1. 调用一次此工具发出第一条消息。
2. 等待工具响应 \`success\` 后，再调用一次此工具发出第二条消息，以此类推。
3. 直到最后一条消息发出后，停止调用此工具。
注意事项：
1. 尽量避免填写 \`reply_to\` 和 \`mention_uids\`，只有在对话复杂、对象不明确、必须精确指向某条消息或某个人时才使用。
2. 如需要明确叫某个人，只填写 \`mention_uids\`，不要在正文里手写 \`@(XXX)\`、\`@某人\`。
`;

/** Tool that enforces JSON output matching the EmaReply shape. */
export class EmaReplyTool extends Tool {
  /** Returns the unique tool name. */
  name = "ema_reply";

  /** Returns the tool purpose and usage guidance. */
  description = EMA_REPLY_TOOL_DESCRIPTION;

  /** Returns the JSON Schema specifying the expected arguments. */
  parameters = EmaReplySchema.toJSONSchema();

  /**
   * Validates and emits a structured reply payload.
   * @param args - Tool arguments matching the reply schema.
   * @param context - Optional tool context (unused).
   */
  async execute(args: unknown, context?: ToolContext): Promise<ToolResult> {
    try {
      const payload = EmaReplySchema.parse(args);
      payload.contents = payload.contents.replaceAll("\\n", "\n");
      return {
        success: true,
        content: JSON.stringify(payload),
      };
    } catch (err) {
      return {
        success: false,
        error: `Invalid structured reply: ${(err as Error).message}`,
      };
    }
  }
}
