name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: pnpm format:check

  test:
    name: Run test
    runs-on: ubuntu-latest
    needs: format-check
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Load MongoDB binary cache
        id: cache-mongodb-binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-binaries
          key: node-mongodb-22

      - name: Install MongoDB
        run: npx tsx scripts/install-mongo.ts
        working-directory: packages/ema

      - name: Run WebUI lint
        run: pnpm --filter ema-webui lint

      - name: Build WebUI
        run: pnpm --filter ema-webui build

      - name: Build Core
        run: pnpm --filter ema build

      - name: Run Vitest
        env:
          GEMINI_API_KEY: "DUMMY_KEY"
        run: pnpm --filter ema test --run --reporter=dot

  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packages/ema-dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --locked

      - name: Run Rust Format Check
        run: cargo fmt --check --all

      - name: Build Rust Docs
        run: cargo doc --workspace --no-deps

  docs-build:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run docs:build
